/******************************************************************************
*  Generated by PSoC Designer 5.3.2710
******************************************************************************/
#include <m8c.h>
// TX address and mask defines
#pragma	ioport	TX_Data_ADDR:	0x0
BYTE			TX_Data_ADDR;
#pragma	ioport	TX_DriveMode_0_ADDR:	0x100
BYTE			TX_DriveMode_0_ADDR;
#pragma	ioport	TX_DriveMode_1_ADDR:	0x101
BYTE			TX_DriveMode_1_ADDR;
#pragma	ioport	TX_DriveMode_2_ADDR:	0x3
BYTE			TX_DriveMode_2_ADDR;
#pragma	ioport	TX_GlobalSelect_ADDR:	0x2
BYTE			TX_GlobalSelect_ADDR;
#pragma	ioport	TX_IntCtrl_0_ADDR:	0x102
BYTE			TX_IntCtrl_0_ADDR;
#pragma	ioport	TX_IntCtrl_1_ADDR:	0x103
BYTE			TX_IntCtrl_1_ADDR;
#pragma	ioport	TX_IntEn_ADDR:	0x1
BYTE			TX_IntEn_ADDR;
#define TX_MASK 0x10
// Key address and mask defines
#pragma	ioport	Key_Data_ADDR:	0x0
BYTE			Key_Data_ADDR;
#pragma	ioport	Key_DriveMode_0_ADDR:	0x100
BYTE			Key_DriveMode_0_ADDR;
#pragma	ioport	Key_DriveMode_1_ADDR:	0x101
BYTE			Key_DriveMode_1_ADDR;
#pragma	ioport	Key_DriveMode_2_ADDR:	0x3
BYTE			Key_DriveMode_2_ADDR;
#pragma	ioport	Key_GlobalSelect_ADDR:	0x2
BYTE			Key_GlobalSelect_ADDR;
#pragma	ioport	Key_IntCtrl_0_ADDR:	0x102
BYTE			Key_IntCtrl_0_ADDR;
#pragma	ioport	Key_IntCtrl_1_ADDR:	0x103
BYTE			Key_IntCtrl_1_ADDR;
#pragma	ioport	Key_IntEn_ADDR:	0x1
BYTE			Key_IntEn_ADDR;
#define Key_MASK 0x20
// RX address and mask defines
#pragma	ioport	RX_Data_ADDR:	0x0
BYTE			RX_Data_ADDR;
#pragma	ioport	RX_DriveMode_0_ADDR:	0x100
BYTE			RX_DriveMode_0_ADDR;
#pragma	ioport	RX_DriveMode_1_ADDR:	0x101
BYTE			RX_DriveMode_1_ADDR;
#pragma	ioport	RX_DriveMode_2_ADDR:	0x3
BYTE			RX_DriveMode_2_ADDR;
#pragma	ioport	RX_GlobalSelect_ADDR:	0x2
BYTE			RX_GlobalSelect_ADDR;
#pragma	ioport	RX_IntCtrl_0_ADDR:	0x102
BYTE			RX_IntCtrl_0_ADDR;
#pragma	ioport	RX_IntCtrl_1_ADDR:	0x103
BYTE			RX_IntCtrl_1_ADDR;
#pragma	ioport	RX_IntEn_ADDR:	0x1
BYTE			RX_IntEn_ADDR;
#define RX_MASK 0x40
// LED address and mask defines
#pragma	ioport	LED_Data_ADDR:	0x4
BYTE			LED_Data_ADDR;
#pragma	ioport	LED_DriveMode_0_ADDR:	0x104
BYTE			LED_DriveMode_0_ADDR;
#pragma	ioport	LED_DriveMode_1_ADDR:	0x105
BYTE			LED_DriveMode_1_ADDR;
#pragma	ioport	LED_DriveMode_2_ADDR:	0x7
BYTE			LED_DriveMode_2_ADDR;
#pragma	ioport	LED_GlobalSelect_ADDR:	0x6
BYTE			LED_GlobalSelect_ADDR;
#pragma	ioport	LED_IntCtrl_0_ADDR:	0x106
BYTE			LED_IntCtrl_0_ADDR;
#pragma	ioport	LED_IntCtrl_1_ADDR:	0x107
BYTE			LED_IntCtrl_1_ADDR;
#pragma	ioport	LED_IntEn_ADDR:	0x5
BYTE			LED_IntEn_ADDR;
#define LED_MASK 0x80
